name: chatbot

services:
  db:
    image: postgres:16
    networks:
      - chatbot_network
    restart: unless-stopped
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: chatbot
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: localpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d  # auto-runs on first start

volumes:
  postgres_data:
networks:
  chatbot_network:
    name: chatbot_network